interpolation:
  enabled: yes
  fps: 720
  speed: medium
  tuning: weak
  algorithm: 23
  use gpu: no

frame blending:
  enabled: yes
  fps: 60
  intensity: 1.0
  weighting: equal

flowblur:
  enabled: no
  amount: 100
  mask:

encoding:
  process: ffmpeg
  loglevel: error
  args: H264 CPU

misc:
  mpv bin: mpv
  stay on top: true
  verbose: false
  ding after: 1
  folder: 
  container: .MP4
  prefix: 
  suffix: fruits
  dedupthreshold: 0

timescale:
  in: 1.0
  out: 1.0

pre interp:
  enabled: no
  factor: 2x
  model: rife-v4.4
