interpolation:
  enabled: true
  fps: 480
  speed: medium
  tuning: weak
  algorithm: 23
  gpu: true
frame blending:
  enabled: true
  fps: 60
  intensity: 1.2
  weighting: equal
flowblur:
  enabled: false
  amount: 100
  mask: None
encoding:
  process: ffmpeg.exe
  args: H264 CPU
misc:
  mpv bin: mpv
  stay on top: true
  verbose: false
  ding after: 0
  folder: None
  container: .mkv
  flavors: fruits
  dedupthreshold: 0.0
timescale:
  in: 1.0
  out: 1.0
