# This is the recipe (config) for making a delicious smoothie ;p
# Learn how it can be fine-tuned @ https://github.com/couleur-tweak-tips/Smoothie/wiki

interpolation:
  enabled: n
  fps: 1920
  mask: cian
  speed: medium
  tuning: weak
  algorithm: 23
  gpu: true

frame blending:
  enabled: y
  fps: 60
  intensity: 1
  weighting: gaussian

flowblur:
  enabled: n
  amount:
  mask:

encoding:
  process: ffmpeg.exe
  args: -c:v utvideo -vf scale=in_range=full:out_range=full

misc:
  mpv bin: mpv
  stay on top: false
  verbose: false
  ding after: 1
  folder: 
  container: .MKV
  flavors: fruits
  dedupthreshold: 

timescale:
  in: 1.0
  out: 1.0