# This is the recipe (config) for making a delicious smoothie ;p
# Learn how it can be fine-tuned @ https://github.com/couleur-tweak-tips/Smoothie/wiki

interpolation:
  enabled: yes
  fps: 480
  speed: medium
  tuning: weak
  algorithm: 23
  gpu: true

frame blending:
  enabled: yes
  fps: 60
  intensity: 1
  weighting: equal

flowblur:
  enabled: no
  amount: 100
  mask:

encoding:
  process: ffmpeg
  args: H264 CPU

misc:
  mpv bin: mpv
  stay on top: true
  verbose: false
  ding after: 1
  folder: 
  container: .MP4
  prefix: 
  suffix: detailed
  dedupthreshold: 0

timescale:
  in: 1.0
  out: 1.0